### ISSUE TITLE
why don't remove img 'lazy' class when is success loaded?

### ISSUE THREAD

**Issue by britrock** [tuupola/jquery_lazyload#268]
when img lazy load images success, remove 'lazy' class, loop through less elements, improve performance.
in my case, scroll to footer, load more images, so when load more than 100 images, the brower slow in android.

**Comment by JoanClaret** [comment]
+1

**Comment by tsm91** [comment]
because it is an overhead, why should you query a dozen of images from the DOM and remove the lazy class?

also, the fadeIn effect is done with js, another overhead, i rather fade-in with css3 transition

```css
img.lazy {
  opacity: 0;
  transition: opacity .15s;

  &[src] { opacity: 1; }
}
```
