### ISSUE TITLE
loading.gif gets streched to full size

### ISSUE THREAD

**Issue by johhansantana** [tuupola/jquery_lazyload#316]
I'm trying to have a loading.gif which is smaller than the actual background-size which is set to cover

is there a way to change the size of the first loading.gif?

``` html
<div class="lazy col-md-6 events-grid-background" data-original="{{path/to/image.jpg}}" ng-style="{'background-image' : 'url(images/loading2.gif)'}">
```

and the css

``` css
.events-grid-background {
  background-size: cover;
  background-position: center;
  background-repeat: no-repeat;
  min-height: 415px;
  border: 1px solid #FFF;
  position: relative;
}
```
